---
- name: 'Install Postgresql packages.'
  yum:
    name: 
      - postgresql-server
      - postgresql-contrib
      - python-psycopg2
    state: present
  become: yes
  tags: prod

- name: 'Postgresql install check.'
  stat:
    path: '{{posgres_pg_hba_path}}'
  register: postgres_data
  tags: prod

- name: 'Postgresql initdb.'
  shell: 'postgresql-setup initdb'
  when: not postgres_data.stat.exists
  become: yes
  tags: prod

- name: 'Enable and start postgresql service.'
  service: 
    name: postgresql
    state: started
    enabled: yes
  become: yes 
  tags: prod
